chaos-genius/chaos_genius

- frontend/src/components/Kpihome/index.jsx
- frontend/src/components/Kpihome/kpihome.scss
Added check for non-numerical % changes for KPI home
> added check for non-numerical perc changes

- chaos_genius/alerts/alert_channel_creds.py
- chaos_genius/alerts/alert_config.py
- chaos_genius/alerts/anomaly_alert_config.py
- chaos_genius/alerts/base_alert_digests.py
- chaos_genius/alerts/base_alerts.py
- chaos_genius/alerts/email.py
- chaos_genius/alerts/slack.py
- chaos_genius/alerts/utils.py
Formatted all the files under the alerts folder
> Alerts format

- frontend/Dockerfile.prod
- frontend/Dockerfile.prod
Recommend upgrading to `nginx:1.21.5-alpine`, as this image has only 0 known vulnerabilities. 
Some of the most important vulnerabilities in our base image include:
| Severity                                                                                                                 | Priority Score / 1000  | Issue                                                                     | Exploit Maturity      |
| :------:                                                                                                                 | :--------------------  | :----                                                                     | :---------------      |
| ![high severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/h.png "high …
> fix: frontend/Dockerfile.prod to reduce vulnerabilities

- chaos_genius/settings.py
> fix: typo in settings.py

- chaos_genius/controllers/kpi_controller.py
- chaos_genius/views/anomaly_data_view.py
- Delete all data in the anomaly_data_output table
- Add the KPI to the queue
> feat(anomaly): added retraining endpoint

- chaos_genius/settings.py
NOTE: this is only a release candidate (rc1), not the final release
> bump version to 0.5.0 for testing

- migrations/versions/4c40273b1dea_.py
Merges JSON->JSONB conversion and the merge of hourly and druid.
Before (two heads):
```
8a84c573b1b6, 5c754059d673 -> 591a00900af9 (head) (mergepoint), empty message <------
890f3e569771 -> 8a84c573b1b6, added timezone aware column to kpi definition
890f3e569771 -> 94a4f2c2b63a (head), change json column to jsonb in the rca data <------
890f3e569771 -> 5c754059d673, created_at for anomaly_data_output
50b793ad398a -> 890f3e569771 (branchpoint), add indexes to triggered alerts table
0382ff889e8d -> 50b793ad398a, added weekly digests column to alert table
24c91089746b, 3165669ea3ec -> 0382ff889e8d (mergepoint), empty message
```
After:
```
94a4f2c2b63a, 591a00900af9 -> 4c40273b1dea (head) (mergepoint), empty message <------
890f3e569771 -> 94a4f2c2b63a, change json column to jsonb in the …
```
> fix(migrations): merge diverged branches

- frontend/src/components/EventAlertForm/index.jsx
Fixed a bug which didn't allow to accept payload during test query in event alerts
> fixed bug which didn't accept test query payload

- .env
- chaos_genius/alerts/constants.py
- chaos_genius/celery_config.py
- chaos_genius/controllers/digest_controller.py
- chaos_genius/templates/digest.html
- Enable the event alert by default
- Enable the hourly event alert
fix https://github.com/chaos-genius/chaos_genius/issues/774
> feat(alerts): enable the hourly event alert

- docker-compose.thirdparty.yml
- docker-compose.yml
Updated the webapp and server docker images from 0.4.1 to 0.5.0 in `docker-compose.yml` and `docker-compose.thirdparty.yml`
> 0.5.0 docker compose update

- frontend/src/components/DashboardGraph/index.jsx
Fix https://github.com/chaos-genius/chaos_genius/issues/819
> changed yAxis property for linechart in DD

- frontend/src/components/AlertTable/index.jsx
Fix: Alerts Delete Popup Name Not Showing #846
> Alert Delete Popup Name Bug 

- frontend/src/components/KpiAlertConfigurationForm/index.jsx
KPI Alert Range bar Not Update Correct value #848
> KPI Alert Range bar value issues fixed

- chaos_genius/alerts/slack.py
- Earlier, the values displayed in slack messages became difficult to comprehend as they grew in magnitude
- The human readable fix is able to mitigate that
> Add human readable format for values in slack messages

- frontend/src/components/KpiExplorerForm/index.jsx
Dropdowns were not getting populated for edit KPI
Solution: Added checks for dropdown populations
> added checks for dropdown populationin edit kpi

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: spell fix for issue template

- chaos_genius/settings.py
- docker-compose.thirdparty.yml
- docker-compose.yml
- Changed docker images tags for the frontend and backend containers from 0.6.0 to 0.6.1 in `docker-compose.yml` and `docker-compose.thirdparty.yml`.
- Changed CG version from 0.6.0 to 0.6.1 in `settings.py`.
> CG 0.6.1 hotfix.

- CONTRIBUTING.md
- GITPOD.md
documented Gitpod and dev docker compose in contributing.
GITPOD.md contains all details on gitpod.
The PR is targeted to main since it's a documentation change.
> docs: add GITPOD.md. overhaul contributing dev workflow.

- chaos_genius/views/alert_view.py
- formatted using black and isort
- fixed type errors
- check the value returned by `get_json()` is None before using it
- returns a message with 400 if it's not a JSON
- fixed flake8 errors
- fixed docstrings
- create a new logger for the alert view module instead of using the root logger (`current_app.logger`)
- reduced total errors and warnings from 60+ to 0
> refactor(alert-view): fix flake8, isort, formatting, type errors

- chaos_genius/views/dashboard_view.py
- formatted with black and isort
- added docstrings for all functions
- validate JSON before using it
- ignore blind except errors
> refactor(dashboard-view): fix type, flake8, isort errors

- docker-compose.thirdparty.yml
- docker-compose.yml
Updated versions in docker compose files
Version in `settings.py` was changed in 1482b6941630748084af49218bc21a5da0b6d020
> release: bumped version to v0.7.0

- chaos_genius/connectors/__init__.py
- chaos_genius/connectors/base_db.py
- chaos_genius/connectors/mysql.py
- chaos_genius/connectors/postgres.py
- chaos_genius/core/utils/data_loader.py
- tests/test_data_loader.py
* Moved SQL identifiers to their respective connectors
* Added Date and timestamp formatting strings in connectors
* Updated data loader to work with these
* Formatted all files used to be consistent with style guidelines.
> Configurable Datetime format and SQL strings in Data Loader

- chaos_genius/connectors/base_db.py
- chaos_genius/core/utils/data_loader.py
* Added configurable dates
* Moved string quotes inside configurable parameters
> Updated data loader time and quotes formatting

- chaos_genius/views/kpi_view.py
> fix(edit-kpi): issue #965 of dashboard getting reset to `All` after editing a KPI.

- chaos_genius/views/kpi_view.py
> Fix bug in edit KPI for NoneType

- chaos_genius/alerts/anomaly_alerts.py
- chaos_genius/alerts/constants.py
- chaos_genius/alerts/email_templates/common.html
- chaos_genius/alerts/email_templates/digest_template.html
- chaos_genius/alerts/email_templates/email_alert.html
See commit messages for details
> Alert fixes post revamp

- chaos_genius/controllers/dashboard_controller.py
- chaos_genius/views/kpi_view.py
Added dashboards list back to kpi list endpoint. This was removed in f2f0c4f61e93b169d3e52b99c531763c4f08db64.
> Fix breadcrumbs in KPI screen

- chaos_genius/alerts/email_templates/common.html
- chaos_genius/controllers/digest_controller.py
Also fixes spacing in email alerts.
> fix(alerts-dashboard): prevent crash when event alerts exist

- chaos_genius/views/anomaly_data_view.py
Fixes #1028
- Use a 3 hour time window (6 points) for hourly KPIs, instead of the default 1 day (48 points).
- The time window could cause multiple entries of the same subdim to be shown in the drilldown. To avoid this, we drop duplicate subdims and keep only the first (after sorting).
> fix(anomaly): smaller time window, drop dups for hourly KPI drilldown

- chaos_genius/views/anomaly_data_view.py
- Formatting (can be ignored for review): 09b74481211b8798f1b9ba41c0fa35790d514f25
- Fix type errors and add missing type annotations: e970130e51f9bf1af3fe585e1604be93891e36aa
- Use local logger instead of global: 24e497d3d882ebb07c69ce692c6259ba893968b2
- Add docstrings: bbdc52d4aff63c116708fab8954a339fd43e3596
- Minor unbound variables error: ee808de40bca40db87115024b3b15c4e9d66b6ed
> refactor anomaly data view for style, lints, type errors

- chaos_genius/core/utils/round.py
- chaos_genius/views/anomaly_data_view.py
> perf: optimize graph JSON creation

- chaos_genius/core/anomaly/controller.py
> fix: added guard condition to fix #1021

- frontend/src/components/Anomaly/index.jsx
- frontend/src/components/DashboardGraph/index.jsx
Name change in the download csv in anomaly and KPI sumary page
> download csv name changes

- migrations/versions/c76670622e1e_add_impact_score.py
Deal with the case when anomaly setting is removed after KPI has run for anomaly.
> fix(anomaly): fix migration 

- chaos_genius/controllers/dashboard_controller.py
- chaos_genius/controllers/data_source_controller.py
Reverts chaos-genius/chaos_genius#1068
> Revert "fix: check dashboard/datasource active in filter options"

- frontend/src/components/Anomaly/index.jsx
> added searchable dimensional and subdimensional value options

- chaos_genius/views/anomaly_data_view.py
This change makes the values in the dropdown in FE sorted too.
> feat(subdim-filter): sort dimension and value lists

- frontend/src/components/DashboardGraph/index.jsx
> Removed xAxis legend of KPI summary chart

- frontend/src/containers/Alerts/index.jsx
Issue: On deletion of Alert, page becomes empty with no Alerts to show Fallback
> called all alerts API when alerts are deleted

- chaos_genius/commands.py
- requirements/dev.txt
- requirements/prod.txt
> Upgrade backend dependencies

- migrations/versions/b176fdcdff99_remove_change_message_and_percent_from_.py
Some very old triggered alerts don't have percent_change.
> fix(migrations): ignore missing percent_change

- .github/workflows/greetings.yml
See: https://github.com/actions/first-interaction/issues/101
> ci: ignore errors in greetings workflow

- frontend/package-lock.json
Reverts chaos-genius/chaos_genius#1143
> Revert "resolved vulnerabilites"

- .github/workflows/greetings.yml
- frontend/package-lock.json
> Revert vuln fixes

- CONTRIBUTING.md
Resolution for two issues while building in local setup.
> Docs: Add troubleshooting guideline for local setup - PIP Version and Python Missing Headers
