chaos-genius/chaos_genius

.env
- CHAOSGENIUS_WEBAPP_URL is now set to http://localhost:8080/
by default in the .env file
=> feat: set default value for CHAOSGENIUS_WEBAPP_URL

dev_workers.sh, requirements/dev.txt, scripts/celery/dev_scheduler.sh, scripts/celery/dev_worker-alerts.sh, scripts/celery/dev_worker-analytics.sh
The single script starts celery scheduler, analytics worker and alerts
worker. It also stops all 3 of them on doing ctrl-c.
Added a new dependency `watchdog` to watch files and restart workers
when there's a code change.
TODO: have a flag to disable auto-reload.
=> feat(dev): add script to run auto-reloading celery workers

chaos_genius/views/anomaly_data_view.py
Changed the anomaly params API to accept hourly scheduler frequency. "H" is the value stored in `scheduler_params`.
This also enables the option in frontend as it is sent through `ANOMALY_PARAMS_META` and will be shown as "Hourly" to the user.
=> feat(anomaly-params): allow hourly scheduler_frequency

chaos_genius/core/utils/kpi_validation.py, chaos_genius/views/kpi_view.py, tests/features/kpi_validation.feature, tests/test_kpi_validation.py
- `validate_kpi` now receives the DataSource object too
- This can be used for datasource-specific behaviour
- Currently, the KPI is assumed to support tz-aware if it's Druid
- Added back timezone-naive check
- This is skipped only if tz-aware is supported (only Druid for now)
- Parsing of datetime column is only done in case of Druid
- Note: this means, the datetime column check is very lax for Druid.
It will accept string, int and floats too. Before this commit,
this behaviour was added for other data sources too.
- Other data sources continue the old behaviour
- Updated tests
- added cases where datetime column is string or is timezone-aware
- added test for Druid-specific KPI
- timezone-aware is accepted in that case
- had to add a new fixture - `extra_kpi_validation_data` to
support …
=>  fix(kpi-validation): skip tz-naive check only for druid and update tests

chaos_genius/jobs/analytics_scheduler.py
Fixes #830
This ensures that `scheduled_time` is always lesser than `last_scheduled_time_rca` if the date, hour, minute and second match exactly. This prevents DeepDrills/Anomaly from being scheduled again if the microsecond component happens to be greater when all other components match.
Tested this on 15 KPIs - none of them displayed the bug.
=> fix(scheduler): remove microsecond component from scheduled_time

chaos_genius/views/data_source_view.py
- as part of Prefetch metadata changes, we started using same apis (`list-schema`, `table-list`, `table-info`) for all 3rd-party or other datasources as opposed to previous branching logic on frontend to call diff apis 
- `table-list` api and `table-info` were not working for 3rd party, the updates here fixes it
=> table-list/table-info handlings incase of 3rd party datasource

chaos_genius/alerts/anomaly_alerts.py, chaos_genius/alerts/email_templates/digest_template.html, chaos_genius/alerts/email_templates/email_alert.html, chaos_genius/alerts/slack.py, chaos_genius/controllers/digest_controller.py
Some fixes made after testing alerts post #836.
1. type issue in `alert_channel_conf` field of `AnomalyPointFormatted` dataclass
1. Removed series_type formatting for previous day data
1. Use strict type versions of int and float to prevent type conversion from str to int/float
1. Make Slack individual alert and email digest formats consistent
=> Post refactor alert fixes

.flake8
Removed ignores in flake8 config. It is a good idea to ignore errors which are hard/impossible to fix in our codebase, but these are very simple fixes.
- E501 is the line length error. Since we have an explicitly defined max line length limit (88 chars), it should be enforced using flake8.
- E203 is whitespace before a colon (https://www.flake8rules.com/rules/E203.html). There's no reason it should be disabled as it is very simple to fix.
- D203 is no blank line before class docstring (https://pep257.readthedocs.io/en/latest/error_codes.html). This too is a simple fix.
=> chore(flake8): remove error ignores

chaos_genius/utils/metadata_api_config.py, chaos_genius/views/data_source_view.py
resolves #864 
as well as :
- earlier (pre-0.5.0) few datasource capabilities (like supported aggregations) were hard-coded on front-end , we had moved in 0.5.0 to a backend api 
- we had tested only non-3rd party and missed handling in case datasource is 3rd party
=> Hotfix 864 (Release v0.5.2)

chaos_genius/alerts/email_templates/README.md, chaos_genius/alerts/email_templates/digest_template.html, chaos_genius/alerts/email_templates/email_alert.html
Fixes #724
- Changed email template of individual and digest email alerts to make the styles inlined into each HTML element. This prevents broken formatting when the email exists in a thread or when it is forwarded.
- Tested locally.
- Also added a README documenting this process.
=> fix(alerts): use inline styles in email templates

docker-compose.fluentd.yml, docker-compose.latest-thirdparty.yml, docker-compose.latest.yml, docker-compose.thirdparty.yml, docker-compose.yml
=> fix(docker): fixes #853 added restart policy

.github/workflows/python-test.yml, scripts/check_diverged_migrations.sh
The script prints a message with the IDs of the two heads if migrations have diverged. Also returns an appropriate error code for CI.
Added this as the last step in CI to check on every PR.
Also removed overridden flake8 arguments in the linting step. We have a `.flake8` config in the project root for these args.
=> chore(ci): add step to check if migrations have diverged

chaos_genius/controllers/digest_controller.py
The alert messages column of event alerts dashboard was empty
Fixes #915
=> Correct event alerts dashboard of missing alert messages

chaos_genius/core/utils/constants.py, chaos_genius/settings.py, docker-compose.thirdparty.yml, docker-compose.yml
- Updated backend and frontend docker images tags from 0.5.2 to 0.6.0 in `docker-compose.yml` and `docker-compose.thirdparty.yml`
- Changed Version from 0.5.2 to 0.6.0 in `settings.py`
=> 0.6.0 version upgrade and avoid misleading timezone deprecation warning

.gitignore, .gitpod.dockerfile, .gitpod.env, .gitpod.yml
Adds configuration for gitpod.
Services started:
- API Server (init part of this can take time due to prophet installation)
- Webapp (opens in a new tab)
- Redis
- Postgres DB (starts before API server)
The `.env` is setup correctly to work out of the box without additional changes.
Python and Jinja plugin are pre-installed in the workspace.
(to use gitpod from this branch) visit https://gitpod.io/#https://github.com/chaos-genius/chaos_genius/tree/gitpod-setup.
You may need to login with GitHub and it takes 5-10mins for setup.
- Please wait for the API server to start up before changing branches (the message will be something like Debugger is active! Debugger PIN: 000-000-000).
- This is needed because gitpod specific files are only present on that branch. Will not be needed once this PR …
=> Setup Gitpod

chaos_genius/views/kpi_view.py
=> fix(editkpi): issue of subdim anomaly failure after removal of all subdims

chaos_genius/views/kpi_view.py
- formatted `kpi_view.py` using black and isort
- fixed some type errors
- check the return value of `request.get_json()` is None before using it
- variable may be unbound - moved initialization to the top. see `ret = []`.
- fixed flake8 errors
- ignored in cases where it cannot be prevented
- fixed flake8 warnings:
- some variables were unused - removed their assignment in case of functions with side effects and removed the entire line in case of functions without side effects (`DataSource.get_by_id` for example)
- isort
- many unused imports
- imports position was wrong
- flask imports require it to be imported from a specific submodule
- added docstrings
- replaced prints with logger
=> refactor(kpi-view): fix flake8, isort, formatting, type errors

chaos_genius/core/anomaly/controller.py
=> chore: fix typo in controller.py

chaos_genius/controllers/kpi_controller.py
- added `Optional[]` to types where missing
- added missing docstrings
- fixed type issues in `run_anomaly_for_kpi`
- renamed `end_date` to help type checker recognize correctly
- added an exception on `else:`
- added ignores to SQLalchemy filters where applicable
- added missing type annotations to `get_anomaly_count`
- formatted using `isort` and `black`
=> refactor(kpi-controller): fix type errors and lint issues

chaos_genius/core/utils/kpi_validation.py
=> Fixes #991 by checking for validation sucess before running checks for tz-aware data

chaos_genius/views/kpi_view.py
=>  fix(edit-kpi): kpi validation triggered on edit kpi

chaos_genius/alerts/email_templates/common.html, chaos_genius/alerts/email_templates/email_alert.html, chaos_genius/alerts/slack.py
- "Sub-dimensional anomalies" heading was present even when there weren't any subdim anomalies in individual alerts.
- "Reasons for change" text was present even when there weren't any relevant subdims.
See diff without code formatting changes: https://github.com/chaos-genius/chaos_genius/compare/06da2ff8345ce0bc7d67c4387aeae1cdeb2c3ceb...fix/alerts-relevant-subdims-empty
=> fix(alerts): wrong formats when subdims were not present

chaos_genius/controllers/digest_controller.py
This was causing an issue where if anomaly was manually disabled by
setting `anomaly_params` to NULL, getting the time series frequency
would fail.
=> fix(alerts-dashboard): consider only alert triggers with anomaly setup

chaos_genius/alerts/anomaly_alerts.py, chaos_genius/alerts/base_alert_digests.py, chaos_genius/alerts/constants.py, chaos_genius/alerts/email.py, chaos_genius/controllers/digest_controller.py, chaos_genius/utils/utils.py
=> feat(alerts): add CSV to email alert report, better CSV names

chaos_genius/views/anomaly_data_view.py
When setting up an hourly anomaly for the first time, `scheduler_params["time"]` does not exist and throws an error in this part of the code.
=> fix(anomaly-params): use .get instead of indexing, check rca_time exists

chaos_genius/core/anomaly/controller.py, chaos_genius/core/rca/rca_controller.py, chaos_genius/core/utils/data_loader.py
Data Loader duplicates the metric column and assigns it a random name if metric and count column are the same.
Anomaly and RCA then read the updated column name for the count column and use it internally.
=> fix(data-loader): fix bug when metric and count column are same

chaos_genius/core/rca/rca_controller.py
Drilldowns failed for other timelines after the first as the count column was overidden.
=> fix(drilldowns): reset count col before data loading

migrations/versions/c76670622e1e_add_impact_score.py
When the KPI did not exist in the kpi table but had anomaly data in the
anomaly_data_output table, the migration would fail with a StopIteration
error as the query did not return rows. This case is handled and the
impact value is set to 0.
=> fix(migration): consider case when KPI was manually deleted

chaos_genius/controllers/digest_controller.py
An extra condition lead to the CSV having only subdim anomalies. When there were no subdim anomalies, the report would fail.
=> fix(alert-report): generate CSV for overall anomalies too

chaos_genius/controllers/dashboard_controller.py, chaos_genius/controllers/data_source_controller.py
These lists are used to populate the filter options in FE.
Fixes #1066
=> fix: check dashboard/datasource active in filter options

chaos_genius/core/anomaly/processor.py
The empty prediction dataframe is now given the correct types immediately after creation. This ensures that any data appended to the dataframe will have the correct type. Note: if the columns or the dataframe itself is overwritten, this will not hold and the types may change.
Also uses a simpler method to get the last row of the prediction dataframe which prevents loss of types. The earlier version would erase all the metadata and make the dtypes `object`.
These 2 changes ensure that the `y` column is always a `float` and the dataframe correctly identifies it as such. Note: the columns can still be overriden by some other code and this cannot be ensured without writing tests.
=> fix(anomaly): ensure correct data types

chaos_genius/core/anomaly/controller.py
=> fix(anomaly): convert slack into hourly value for hourly KPIs

.github/workflows/python-test.yml, Dockerfile, requirements/dev.txt, requirements/prod.txt
`sqlalchemy-bigquery` had to be added directly from a PR fixing the dependencies which has not yet been merged: https://github.com/googleapis/python-bigquery-sqlalchemy/pull/479
=> chore(deps): upgrade datasource deps and resolve conflicts

.github/dependabot.yml
Some version upgrades are deferred, which blocks other version upgrades unnecessarily.
=> chore: increase dependabot pip PR limit to 10

requirements/prod.txt
bump python libraries:
- pytz from `2022.1` to `2022.2.1`
- pandas from `1.3.5` to `1.4.4`
- statsmodels from `0.12.2` to `0.13.2`
- prophet from `1.0.1` to `1.1`
- remove pystan
Testing:
=> Upgrade analytics libraries

frontend/src/components/EventAlertForm/index.jsx
Event alerts form should show toast in test query
=> Bug event alert toast on test query

chaos_genius/connectors/base_db.py
Before applying our own `LIMIT 1`, we check if the query already has a `LIMIT` clause by a simple substring search. This had two issues:
- It did not work when `LIMIT` was in uppercase
- It could match "limit" in a column or table name
Changed this to use a case-insensitive regex search which also looks for whitespace around `LIMIT`. Since "limit" as a column or table name will need to enclosed in double quotes, this regex will not match them.
=> fix(datasource): use case-insensitive check for LIMIT

chaos_genius/alerts/base_alert_digests.py
When an alert is made inactive or deleted, the previously triggered alerts were still being included in the alert report.
Fix this by ignoring and logging the triggered alert if it's from an alert that is inactive or deleted.
=> fix(alert-report): ignore trig alerts of deleted/inactive alerts

requirements/prod.txt
Reverts chaos-genius/chaos_genius#1134
`snowflake-connector-python` does not support pandas 1.5.0 yet. See: https://github.com/chaos-genius/chaos_genius/actions/runs/3104998273/jobs/5030104548#step:4:387
=> Revert "chore(deps): bump pandas from 1.4.4 to 1.5.0"

chaos_genius/alerts/anomaly_alerts.py, chaos_genius/alerts/constants.py, chaos_genius/alerts/email_templates/common.html, chaos_genius/alerts/slack.py, chaos_genius/alerts/utils.py, chaos_genius/templates/alert_dashboard.html, migrations/versions/b176fdcdff99_remove_change_message_and_percent_from_.py
=> Alerts changes for expected value addition

chaos_genius/controllers/alert_controller.py, chaos_genius/views/anomaly_data_view.py
- Before re-training, the triggered alerts data from T-offset is deleted and the `last_anomaly_timestamp` is set to one unit lesser than T-offset (unit depends on the anomaly frequency).
- See new functions: `clear_triggered_alerts_from_offset`, `set_last_anomaly_timestamp_to_offset`
- See new code in `kpi_anomaly_retraining` in `anomaly_data_view`
=> fix(retrain): clear recent alerts data and set appropriate last_anomaly_timestamp

chaos_genius/alerts/anomaly_alerts.py
A bug existed that appeared in this case:
- An alert is set up with subdims disabled and set to digest/report
- For the same day, both overall and subdim anomalies are present - (same hour in case of hourly alerts)
The bug:
The digest/report sent on that day included subdim anomalies for that KPI in the "Top sub-dimensional anomalies" section even though subdims was disabled.
The cause:
The subdims inside of relevant_subdims were being considered even if include_subdims was set to false. This did not affect subdims that were not associated with an overall anomaly.
The fix:
Add the include_subdims condition to subdims inside relevant_subdims too.
=> fix(alerts): consider subdims inside relevant only if enabled

chaos_genius/alerts/utils.py
When expected value was negative, the percent change would be in the opposite direction of what it should be.
Fixed by using absolute value of expected value in the denominator.
Tested on these cases:
- Both positive: actual higher than expected
- Both positive: actual lower than expected
- Actual positive and expected negative
- Actual negative and expected positive
- Both negative: actual higher than expected
- Both negative: actual lower than expected
=> fix(alerts): ensure percent change is not flipped for neg. exp. vals
